[package]
name = "crypto"
version = "0.1.0"
authors = ["Jedrzej Stuczynski <andrew@nymtech.net"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.1"
bs58 = "0.4.0"
blake3 = { version = "1.3.1", features = ["traits-preview"] }
ctr = "0.9.1"
digest = "0.10.3"
generic-array = "0.14"
hkdf = "0.12.3"
hmac = "0.12.1"
cipher = "0.4.3"
x25519-dalek = "1.1"
ed25519-dalek = "1.0"
log = "0.4"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
subtle-encoding = { version = "0.5", features =  ["bech32-preview"]}

# internal
nymsphinx-types = { path = "../nymsphinx/types" }
pemstore = { path = "../../common/pemstore" }
config = { path="../../common/config" }
